#      ____  __           __  _______                     ____
#    / __ )/ /___  _____/ /_/_  __(_)___ ___  ___  _____/ __ \___  ____ ___  ____ _   _____  _____
#   / __  / / __ \/ ___/ //_// / / / __ `__ \/ _ \/ ___/ /_/ / _ \/ __ `__ \/ __ \ | / / _ \/ ___/
#  / /_/ / / /_/ / /__/ ,<  / / / / / / / / /  __/ /  / _, _/  __/ / / / / / /_/ / |/ /  __/ /
# /_____/_/\____/\___/_/|_|/_/ /_/_/ /_/ /_/\___/_/  /_/ |_|\___/_/ /_/ /_/\____/|___/\___/_/
#
# This file is part of BlockTimerRemover (Bukkit).
#
# BlockTimerRemover is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Remember to join my Discord server if you need help:
# https://discord.nookure.com/
#
# General configuration for the plugin.
#
Config:
  # Enable or disable the debug mode.
  # If enabled, the plugin will send more information about the plugin status.
  debug: false